function symOmegas = fooFile(in1,in2,in3)
%fooFile
%    symOmegas = fooFile(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Dec-2021 15:55:13

OD5 = in3(5,:);
OD11 = in3(11,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
q7 = in1(7,:);
q8 = in1(8,:);
q9 = in1(9,:);
q10 = in1(10,:);
q11 = in1(11,:);
q12 = in1(12,:);
q13 = in1(13,:);
q14 = in1(14,:);
w3 = in2(3,:);
w14 = in2(14,:);
mt1 = [q1.*abs(q1).*2.906499427819522e-2,q2.*abs(q2).*1.160968127883829e-2,q3.*w3.*(-4.0e-4)+q3.*abs(q3).*3.55e-2-w3.^2./1.0e+4,q4.*abs(q4).*1.160968127883829e-2,1.0./OD5.^2.*q5.*abs(q5)];
mt2 = [q6.*abs(q6).*2.906499427819522e-2,q7.*abs(q7).*2.906499427819522e-2,q8.*abs(q8).*3.797398324550851e-1,q9.*abs(q9).*1.160968127883829e-2];
mt3 = [q10.*abs(q10).*2.906499427819522e-2,1.0./OD11.^2.*q11.*abs(q11),q12.*abs(q12).*4.989071614340439e-1,q13.*abs(q13).*1.414051744971674e-1,q14.*w14.*(-4.0e-4)+q14.*abs(q14).*3.55e-2-w14.^2./1.0e+4];
symOmegas = [mt1,mt2,mt3];
